Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  find: `phone/java': No such file or directory
find: `phone/java': No such file or directory
find: `dummy': No such file or directory
In file included from hardware/libhardware_legacy/audio/AudioPolicyManagerDefault.h:21:0,
                 from hardware/libhardware_legacy/audio/AudioPolicyManagerDefault.cpp:20:
hardware/libhardware_legacy/include/hardware_legacy/AudioPolicyManagerBase.h:291:18: error: redeclaration of 'bool android_audio_legacy::AudioPolicyManagerBase::AudioOutputDescriptor::mForceRouting'
             bool mForceRouting; // Next routing for this output will be forced as current device routed is null
                  ^
hardware/libhardware_legacy/include/hardware_legacy/AudioPolicyManagerBase.h:289:18: note: previous declaration 'bool android_audio_legacy::AudioPolicyManagerBase::AudioOutputDescriptor::mForceRouting'
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1